package com.example.wonderfulnature;

import java.util.ArrayList;

public class AllNatureData {
    public static String[][] data = new String[][]{
            {"Angel Falls, Venezuela", "The world's highest waterfall—the 3,212-foot cascades of Angel Falls", "https://media.cntraveler.com/photos/5cb63a087b743b471660a8da/master/w_820,c_limit/Angel-Falls-Venezuela_GettyImages-165513023.jpg", "Venezuela overflows with natural wonders, including the world's highest waterfall—the 3,212-foot cascades of Angel Falls, located in the UNESCO-protected Canaima National Park. Canaima is by far the country's most popular attraction, and the falls stretch an astounding 19 times higher than Niagara Falls. Bonus: Pixar animators used the location as inspiration for Paradise Falls in Up—so you know it's good.", "Salto Ángel", "Venezuela", "GMT-4", "5°58′03″N 62°32′08″W"},
            {"Cabo San Lucas, Mexico", "Home to 67 national parks, more than 5,000 miles of coastline", "https://media.cntraveler.com/photos/5cb63a0a515ac842773761a9/master/w_820,c_limit/Baja-Sur-Cabo-San-Lucas-Mexico_GettyImages-988332844.jpg", "Home to 67 national parks, more than 5,000 miles of coastline, and landscapes ranging from deserts to snow-capped volcanoes, Mexico is so much more than the stuff of spring break clichés. Case in point: Cabo San Lucas. Venture outside of your all-inclusive resort to experience the region's turquoise waters, marine life, and iconic Arch of Cabo San Lucas, standing where the Gulf of California meets the Pacific Ocean.", "Saint Luke Cape", "Mexico", "UTC-7", "22°53′23″N 109°54′56″W"},
            {"Antelope Canyon, Arizona", "The narrow, undulating spaces between rock formations", "https://media.cntraveler.com/photos/5cb63a076b5c4d5dcc5ec14a/master/w_820,c_limit/Antelope-Canyon-AZ_GettyImages-164342990.jpg", "Antelope Canyon is a slot canyon (and serious Instagram darling) in the American Southwest. Its Navajo name translates to “the place where water runs through rocks”—an allusion to the canyon’s creation through erosion. The narrow, undulating spaces between rock formations allow for vivid patterns when sunlight filters through the striated stone.", "\"Upper Antelope Canyon\"", "Arizona", "GMT-7", "36°57′10″N 111°26′29″W"},
            {"Atacama Desert, Chile", "Years of erosion have left behind jagged peaks", "https://media.cntraveler.com/photos/5cb896b82721dd144b749295/master/w_820,c_limit/GettyImages-rh94-1911.jpg", "Have you ever dreamed of exploring the moon? A trip to Valle de la Luna in Chile’s Atacama Desert is a much shorter flight. Years of erosion have left behind jagged peaks, dry riverbeds, and a landscape startlingly similar to that of our favorite celestial body's.", "Desierto de Atacama", "Chile", "GMT-4", "24°30′S 69°15′W "},
            {"Arashiyama Bamboo Grove, Japan", "Japanese bamboo garden", "https://media.cntraveler.com/photos/5cb63a091a7e70293bf7094b/master/w_820,c_limit/Arashiyama-Japan_GettyImages-687644524.jpg", "Every traveler should experience the ethereal glow and seemingly endless heights of this bamboo grove on the outskirts of Kyoto. The experience even extends beyond the visual realm: In 1996, Japan's Ministry of the Environment included the sounds here—wood creaking, leaves rustling—as one of the top 100 Soundscapes of Japan.", "Sagano Bamboo Forest", "Japan", "GMT+9", "35°00'34.9\"N 135°40'00.2\"E"},
            {"Avenue of the Baobabs, Madagascar", "Separated from continental Africa by 250 miles of water", "https://media.cntraveler.com/photos/5cb63e5611a45ee15630373e/master/w_820,c_limit/Baobabs_GettyImages-889836156.jpg", "Separated from continental Africa by 250 miles of water, Madagascar is the greatest adventure you haven't had yet. The island nation's secrets include giant moths, bug-eyed lemurs, and places like the surreal Avenue of the Baobabs, where the centuries-old trees reach heights of nearly 100 feet.", "Alley of the Baobabs", "Madagascar", "GMT+3", "20°15′3″S 44°25′6″E"},
            {"The Azores, Portugal", "The verdant valleys, steep ocean-side cliffs", "https://media.cntraveler.com/photos/5cb63a096b5c4d35405ec14c/master/w_820,c_limit/Azores-Portugal_GettyImages-593462283.jpg", "Roughly 900 miles off the coast of Lisbon, this Portuguese archipelago can inspire wanderlust with a single photo. The verdant valleys, steep ocean-side cliffs, rows of blue hydrangeas, and scattering of waterfalls make the Azores a paradise worth exploring—just make sure you visit before everyone you know beats you to it.", "Região Autónoma dos Açores", "Portugal", "UTC-1", "38.6°N 28°W"},
            {"Banff National Park, Canada", "Banff National Park overwhelms with views of the Canadian Rockies and regular cast of wildlife.", "https://media.cntraveler.com/photos/5cb63a0bc131b962ade953ad/master/w_820,c_limit/Banff-Canada_GettyImages-680900749.jpg", "Easily one of the most beautiful spots in Canada, Banff National Park overwhelms with views of the Canadian Rockies and regular cast of wildlife. The park is also known for its abundance of beautiful lakes, including Lake Louise, Moraine Lake, and glacial Lake Minnewanka—each more pristine than the last.", "Parc national Banff", "Canada", "UTC-6", "51.5°N 116.0°W"},
            {"Boracay, Philippines", "With its gentle coastlines and transporting sunsets", "https://media.cntraveler.com/photos/5cb63a0bc131b97747e953af/master/w_820,c_limit/Boracay-Philippines_GettyImages-657020958.jpg", "With its gentle coastlines and transporting sunsets, it's easy to see why Boracay was voted one of the best islands in the world by our readers. Unfortunately, it's become too touristed—the island closed for \"rehabilitation\" last year to compensate for overcrowding and unregulated development; it's since reopened to a limited number of visitors per day.", "-", "Philippines", "GMT+8", "11°58′8″N 121°55′26″E"},
            {"Boulders Beach, South Africa", "Located on the False Bay Coastline, about 17 miles south of Table Mountain", "https://media.cntraveler.com/photos/5cb63a0b11a45e11b830372e/master/w_820,c_limit/Boulders-Beach-South-Africa_GettyImages-902051250.jpg", "Located on the False Bay Coastline, about 17 miles south of Table Mountain, Boulders Beach shows off Cape Town's famously beautiful landscapes—bright blue water, granite boulders, and... penguins! Many people swim here just a few feet away from the adorable African penguin community, but feel free to just sit back and admire the beautiful coastline as well.", "-", "South Africa", "UTC+2", "34 197°S 18 451°E"}
    };

    public static ArrayList<Nature> getDataNature() {
        Nature nature = null;
        ArrayList<Nature> list = new ArrayList<>();
        for (String[] natureData : data) {
            nature = new Nature();
            nature.setThe_title(natureData[0]);
            nature.setShort_description(natureData[1]);
            nature.setPhoto(natureData[2]);
            nature.setLong_description(natureData[3]);
            nature.setOther_name(natureData[4]);
            nature.setLocation(natureData[5]);
            nature.setTime_zone(natureData[6]);
            nature.setCoordinates(natureData[7]);
            list.add(nature);
        }
        return list;
    }
}
